version: "3"
services:
  airports:
    image: djbnjack/airports
    networks:
      - airports
  countries:
    image: djbnjack/countries
    networks:
      - countries
  haproxy:
    image: djbnjack/haproxy
    ports: ["8000:8000"]
    networks:
      - countries
      - airports

networks:
  airports:
  countries:
