apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: haproxy
    spec:
      containers:
      - image: djbnjack/haproxy
        name: haproxy
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
