version: "3.7"
services:
  airports:
    image: airports
    build: ../services/airports
    ports:
      - "8081:8080"
  countries:
    image: countries
    build: ../services/countries
    ports:
      - "8080:8080"
