version: "3.7"
services:
  airports:
    image: airports
    build: ../services/airports
    networks:
      - airports
  countries:
    image: countries
    build: ../services/countries
    networks:
      - countries
  haproxy:
    image: haproxy
    build: ../services/haproxy
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    networks:
      - countries
      - airports

networks:
  airports:
  countries:
